// <auto-generated />
using System;
using ContactManager.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContactManager.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260527134342_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContactManager.API.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("Favorite")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "New York",
                            Company = "Google",
                            CreatedAt = new DateTime(2026, 5, 27, 13, 43, 41, 574, DateTimeKind.Utc).AddTicks(5259),
                            Email = "john@example.com",
                            Favorite = true,
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "9876543210"
                        },
                        new
                        {
                            Id = 2,
                            Address = "California",
                            Company = "Microsoft",
                            CreatedAt = new DateTime(2026, 5, 27, 13, 43, 41, 574, DateTimeKind.Utc).AddTicks(5262),
                            Email = "jane@example.com",
                            Favorite = false,
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "9123456780"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
