version: '3.9'

services:
  # ── Backend API ──────────────────────────────────────────────────────────────
  backend:
    build:
      context: ./backend/ContactManager.API
      dockerfile: Dockerfile
    container_name: contact-manager-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=db.biqogjsuhyygdsiypkbp.supabase.co;Port=5432;Database=postgres;Username=postgres;Password=viishal95501;SSL Mode=Require;Trust Server Certificate=true
    restart: unless-stopped
    networks:
      - contact-net

  # ── Frontend ─────────────────────────────────────────────────────────────────
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: contact-manager-ui
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - contact-net

networks:
  contact-net:
    driver: bridge
